### ISSUE TITLE
Error(s) executing commands based on JBang on Windows due to single-quotes

### ISSUE THREAD

**Issue by d4ljoyn** [camel-tooling/camel-dap-client-vscode#467]
I get this output with the default install of the extension, see my hack below

*  Executing task: jbang '-Dcamel.jbang.version=3.21.0' camel@apache/camel run 'topsmon.camel.yaml' --dev --logging-level=info  

[jbang] [ERROR] Script or alias could not be found or read: ''-Dcamel.jbang.version=3.21.0''
[jbang] Run with --verbose for more details

I removed the single quotes from  CamelJBangTaskProvider.js:34 and then it works

 *  Executing task: jbang -Dcamel.jbang.version=3.21.0 camel@apache/camel run topsmon.camel.yaml --dev --logging-level=info  

2023-08-12 09:57:38.709  INFO 4588 --- [           main] org.apache.camel.main.MainSupport   : Apache Camel (JBang) 3.21.0 is starting
2023-08-12 09:57:38.864  INFO 4588 --- [           main] org.apache.camel.main.MainSupport   : Using Java 17.0.8 with PID 4588. Started by dave in C:\Source\LocalDev\camel\topsmon

I tried with Powershell and got the same error just in case it had to do with my choice of terminal

**Comment by apupier** [comment]
We have an automated test executing successfully the Run, including on Windows, https://github.com/camel-tooling/camel-dap-client-vscode/actions/runs/5793667731/job/15738852194#step:14:85

@d4ljoyn Can you precise which Windows version you are using please? Can you precise which way you are using to call the command? (From command-palette/quick action/codelens, maybe reproducing with all?)

**Comment by d4ljoyn** [comment]
It is windows 11 and I am even able to reproduce that on the cmd box
with quotes:

![image](https://github.com/camel-tooling/camel-dap-client-vscode/assets/1335362/7e85eaca-464d-49ad-93b9-99a3d0b1dfbe)

without quotes:

![image](https://github.com/camel-tooling/camel-dap-client-vscode/assets/1335362/01c52a28-bf46-4784-951d-64862ca03097)

Anyway I have a workaround for it -- still it is a bit strange.  Thanks for the great tool -- very useful!
Regards

**Comment by unsortedhashsets** [comment]
Hi @d4ljoyn,

I am interested to know which terminal you use by default in VS Code - is it `cmd`, `PowerShell`, or `Windows PowerShell`?

It looks like the problem exists specifically in the case of `cmd` and `single quote`, which means cmd somehow double single quotes :thinking: 

BTW with double quotes in command `cmd` works too
